# This is a basic workflow to help you get started with Actions

name: Simple Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install
      - uses: actions/checkout@v2
        with:
          cmd: yarn install
          
      - name: Build
      - uses: actions/checkout@v2
        with:
          cmd: CI=false yarn run build # will run `yarn build` command
          
          
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command

